config/routes.rb
Seeu::Application.routes.draw do

  # RESTful routes
  resources :manufacturers do
    resources :models
  end

  resources :rules

  resources :actuators do
	  resource :commands
  end

  resources :sensors do
	  resources :readings
  end

  # routes that retrieve information about sensors and actuators via JSON
  match '/sensors/:id/valid_values' => 'sensors#valid_values'
  match '/sensors/:id/valid_values_string' => 'sensors#valid_values_string'
  match '/sensors/get_id_from_name/:name' => 'sensors#get_id_from_name'
  match '/sensors/get_values_from_name/:name' => 'sensors#get_values_from_name'
  match '/sensors/get_values_string_from_name/:name' => 'sensors#get_values_string_from_name'

  match '/actuators/:id/valid_values' => 'actuators#valid_values'
  match '/actuators/:id/valid_values_string' => 'actuators#valid_values_string'
  match '/actuators/get_values_from_name/:name' => 'actuators#get_values_from_name'

  # machine readable page (only the command--no additional markup)
  match '/actuators/:id/command' => 'commands#command'

  # feedback and about
  match 'feedback', :to => 'home#feedback', :as => 'feedback'
  match 'about', :to => 'home#about', :as => 'about'
  match 'study', :to => 'home#study', :as => 'study'

  # set the document root to app/view/home/index.html.erb
	root :to => "home#index"

  # route all invalid URLs to document root
  match '*a' => redirect('/') # send all random routes to root
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
		@sensors = Sensor.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 20 || 1
		@actuators = Actuator.paginate :page => params[:page], :order => 'created_at DESC', :per_page => 20 || 1
		@rules = Rule.all
	
		respond_to do |format|
			format.html
			format.xml { render :xml => @sensors }
		end
	end

  def about

		respond_to do |format|
			format.html
			format.xml { render :xml => @sensors }
		end
  end

  def feedback 

		respond_to do |format|
			format.html
			format.xml { render :xml => @sensors }
		end
  end

  def study

		respond_to do |format|
			format.html
			format.xml { render :xml => @sensors }
		end
  end


end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_sensor.html.erb
<%= render(:partial => "sensor", :object => @sensors.last) %>

	<% for sensor in @sensors %>
 	<div class="<%= cycle('device-entry-odd', 'device-entry-even') %>">
 		Name: <%= link_to sensor.name, sensor_path(sensor) %><br/>
		<img src="images/<%=h sensor.model %>.jpg"/><br/>
 		Description: <%=h sensor.description %><br/>
   	Recent Readings:<br/>
    <hr/>
    <div id="readings">
      <%= render sensor.readings.reverse[0..2] %>
    </div> <!-- readings -->
    <hr/>

   	<ul>
			<% sensor.readings.reverse.each_with_index do |reading, count| %>
	 		<li>Reading: <%=h reading.data %></li>
	 		<% break if count >= 2 %>
  		<% end %>
 		</ul>
		Config URI: <a href="<%=h sensor.configuration_uri %>"><%=h sensor.configuration_uri %></a><br/>
 		</div> <!-- entry -->
   	<% end %>

app/views/home/about.html.erb
<% title "About" %>

<br/>
<div>
  Sensor Enablement for End-Users (SEEU) is the PhD work of <%= link_to 'Seth Holloway', 'http://www.sethholloway.com/' %> under the direction of <%= link_to 'Dr. Christine Julien', 'http://www.ece.utexas.edu/~julien/' %> of the <%= link_to 'Mobile and Pervasive Computing Group', 'http://mpc.ece.utexas.edu/' %> at <%= link_to 'The University of Texas at Austin', 'http://www.utexas.edu/' %>

  Have an opinion? Give us your <%= link_to 'feedback', feedback_path %>!
</div>

app/views/home/feedback.html.erb
<% title "Feedback" %>

<br/>
<div>
  <iframe src="https://spreadsheets.google.com/embeddedform?formkey=dDhZM1Y3d0NfRnB4VWNRVmpVSzgwa2c6MQ" width="760" height="1200" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>
</div>

app/views/home/index.html.erb
<% title "Home" %>

<!-- ####### -->
<!-- SENSORS -->
<!-- ####### -->
<div id="left-box">
	<span class="box-heading"><%= link_to 'Sensors', sensors_path %></span>

    <%= render :partial => "sensors/sensor", :collection => @sensors[0..3] %>

	<% if @sensors.length > 4 %>
	<div class="more">
		<%= link_to "... the other sensors (#{@sensors.length-4})", sensors_path %>
	</div>
	<% end %>
</div> <!-- left-box -->


<!-- ######### -->
<!-- ACTUATORS -->
<!-- ######### -->
<div id="right-box">
	<span class="box-heading"><%= link_to 'Actuators', actuators_path %></span>

    <%= render :partial => "actuators/actuator", :collection => @actuators[0..4] %>

	<% if @actuators.length > 5 %>
	<div class="more">
		<%= link_to "... the other actuators (#{@actuators.length-5})", actuators_path %>
	</div>
	<% end %>
</div> <!-- right box -->


<div style="clear:both"></div>
<hr/>


<!-- ##### -->
<!-- RULES -->
<!-- ##### -->
<div id="rules">
	<span class="box-heading"><%= link_to 'Rules', rules_path %></span>

    <%= render :partial => "rules/rule", :collection => @rules[0..4] %>

	<% if @rules.length > 5 %>
	<div class="more">
		<%= link_to "... the other rules (#{@rules.length-5})", rules_path %>
	</div>
	<% end %>
</div> <!-- rules -->

app/views/home/study.html.erb
<% title "Study" %>

<br/>
<div>
  Sensor Enablement for End-Users (SEEU) is the PhD work of <%= link_to 'Seth Holloway', 'http://www.sethholloway.com/' %> under the direction of <%= link_to 'Dr. Christine Julien', 'http://www.ece.utexas.edu/~julien/' %> of the <%= link_to 'Mobile and Pervasive Computing Group', 'http://mpc.ece.utexas.edu/' %> at <%= link_to 'The University of Texas at Austin', 'http://www.utexas.edu/' %><br/>

  Start the server<br/>
  Deploy the SPOT devices<br/>

  Have an opinion? Give us your <%= link_to 'feedback', feedback_path %>!
</div>