config/routes.rb
Seeu::Application.routes.draw do

  # RESTful routes
  resources :manufacturers do
    resources :models
  end

  resources :rules

  resources :actuators do
	  resource :commands
  end

  resources :sensors do
	  resources :readings
  end

  # routes that retrieve information about sensors and actuators via JSON
  match '/sensors/:id/valid_values' => 'sensors#valid_values'
  match '/sensors/:id/valid_values_string' => 'sensors#valid_values_string'
  match '/sensors/get_id_from_name/:name' => 'sensors#get_id_from_name'
  match '/sensors/get_values_from_name/:name' => 'sensors#get_values_from_name'
  match '/sensors/get_values_string_from_name/:name' => 'sensors#get_values_string_from_name'

  match '/actuators/:id/valid_values' => 'actuators#valid_values'
  match '/actuators/:id/valid_values_string' => 'actuators#valid_values_string'
  match '/actuators/get_values_from_name/:name' => 'actuators#get_values_from_name'

  # machine readable page (only the command--no additional markup)
  match '/actuators/:id/command' => 'commands#command'

  # feedback and about
  match 'feedback', :to => 'home#feedback', :as => 'feedback'
  match 'about', :to => 'home#about', :as => 'about'
  match 'study', :to => 'home#study', :as => 'study'

  # set the document root to app/view/home/index.html.erb
	root :to => "home#index"

  # route all invalid URLs to document root
  match '*a' => redirect('/') # send all random routes to root
end

app/models/actuator.rb
class Actuator < ActiveRecord::Base
  has_one :command, :dependent => :destroy, :autosave => true
  cattr_reader :per_page
  @@per_page = 10

  #after_create :create_command

  def self.get_id_from_name(input="")
    input.gsub("%20"," ").gsub("%23","#")
    @actuator = self.where('name like ?', input).first
    return @actuator.id
  end

  def self.valid_value_range()
    @ends = self.valid_values.gsub("-","..").split("..").map{|s| s.to_i}
    return Range.new(@ends[0],@ends[1])
  end

  def valid_value_range()
    @vals = self.valid_values
    if (@vals.index(".."))
      @ends = @vals.split("..").map{|s| s.to_i}
      return Range.new(@ends[0],@ends[1])
    elsif (@vals.index(","))
      @ends = @vals.split(",")
      return @ends
    else
      return Range.new(0,1)
    end
  end


  private
	def create_command
	  Command.create(:actuator => self)
	end
end

app/controllers/actuators_controller.rb
class ActuatorsController < ApplicationController
  # GET /actuators
  # GET /actuators.xml
  def index
    @actuators = Actuator.paginate :per_page => 5, :page => params[:page], :order => 'created_at DESC' || 1

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @actuators }
    end
  end

  # GET /actuators/1
  # GET /actuators/1.xml
  def show
    @actuator = Actuator.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @actuator }
    end
  end

  # GET /actuators/new
  # GET /actuators/new.xml
  def new
    @actuator = Actuator.new
		@actuator.command = Command.new #unless @actuator.command

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @actuator }
    end
  end

  # GET /actuators/1/edit
  def edit
    @actuator = Actuator.find(params[:id])
  end

  # POST /actuators
  # POST /actuators.xml
  def create
    @actuator = Actuator.new(params[:actuator].each_value(&:strip!))
    @actuator.command = Command.new

    #if @actuator.save
    #  @actuator.data_uri = actuator_commands_path(@atuator)
    #  @actuator.configuration_uri = actuator_path(@actuator)
    #end 

    respond_to do |format|
      if @actuator.save
        format.html { redirect_to(@actuator, :notice => 'Actuator was successfully created.') }
        format.xml  { render :xml => @actuator, :status => :created, :location => @actuator }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @actuator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /actuators/1
  # PUT /actuators/1.xml
  def update
    @actuator = Actuator.find(params[:id])

    respond_to do |format|
      if @actuator.update_attributes(params[:actuator].each_value(&:strip!))
        format.html { redirect_to(@actuator, :notice => 'Actuator was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @actuator.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /actuators/1
  # DELETE /actuators/1.xml
  def destroy
    @actuator = Actuator.find(params[:id])
    @actuator.destroy

    respond_to do |format|
      format.html { redirect_to(actuators_url) }
      format.xml  { head :ok }
    end
  end

  def get_values_from_name
    @actuator_id = Actuator.get_id_from_name(params[:name])
    @actuator = Actuator.find(@actuator_id)
    @vv = @actuator.valid_values # this returns the string representation of valid values
    @vvr = @actuator.valid_value_range() # this returns the range of valid values

    respond_to do |format|
      format.html { @vv }
      format.json { render :json => { :valid_values => @vv } }
    end
  end

  def valid_values
    @actuator = Actuator.find(params[:id])
    @vv = @actuator.valid_values # this returns the string representation of valid values
    @vvr = @actuator.valid_value_range() # this returns the range of valid values

    respond_to do |format|
      format.html { @vv }
      format.json { render :json => @vvr }
    end
  end

  def valid_values_string
    @actuator = Actuator.find(params[:id])
    @vv = @actuator.valid_values # this returns the string representation of valid values
    @vvr = @actuator.valid_value_range() # this returns the range of valid values

    respond_to do |format|
      format.html { @vv }
      format.json { render :json => { :valid_values => @vv } }
    end
  end

end

app/helpers/actuators_helper.rb
module ActuatorsHelper
end

app/views/actuators/_actuator.html.erb
    <div class="<%= cycle('device-entry-odd', 'device-entry-even') %>">
        <div class="device-name">
            <%= link_to actuator.name, actuator_path(actuator) %>
        </div> <!-- device-name -->

        <div class="device-image">
            <img src="images/<%=h actuator.model.downcase %>.jpg"/>
        </div> <!-- device-image -->

        <div class="device-description">
            <%= truncate(strip_tags(actuator.description), :length => 140) %><br/>

            <% unless actuator.command.nil? or actuator.command.data.nil? %>
            <div class="device-readings">
                <%= link_to "Command", actuator_commands_path(actuator) %>:
                <%= actuator.command.data %>
            </div> <!-- device-readings -->
            <% end %>
        </div> <!-- device-description -->

        <div style="clear:both"></div>

        <div style="display:none">
            Config URI: <a href="<%=h actuator.configuration_uri %>"><%=h actuator.configuration_uri %></a>
        </div>
    </div> <!-- device-entry -->

app/views/actuators/_form.html.erb
<%= form_for(@actuator) do |f| %>
  <% if @actuator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@actuator.errors.count, "error") %> prohibited this actuator from being saved:</h2>

      <ul>
      <% @actuator.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :rows => 3 %>
  </div>
  <div class="field">
    <%= f.label :manufacturer %><br />
    <%= f.text_field :manufacturer %>
  </div>
  <div class="field">
    <%= f.label :model %><br />
    <%= f.text_field :model %>
  </div>
  <div class="field">
    <%= f.label :valid_values %><br />
    <%= f.text_field :valid_values %> (ranges: number1..number2 OR states: value1,value2,value3)
  </div>
  
<div style="display:none">
  <div class="field">
    <%= f.label :data_uri %><br />
    <%= f.text_field :data_uri %>
  </div>
  <div class="field">
    <%= f.label :configuration_uri %><br />
    <%= f.text_field :configuration_uri %>
  </div>
</div> <!-- display:none -->

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/actuators/edit.html.erb
<% title "Editing Actuator" %>

<div class="yield">
<h1>Editing actuator</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Home', root_path %> |
<%= link_to 'Actuators', actuators_path %> |
<%= link_to 'Back', @actuator %>
</div> <!-- .yield -->

app/views/actuators/index.html.erb
<% title "Actuators" %>

<div class="yield">
<h1>Listing actuators</h1>

<%= render @actuators %>
<%= will_paginate @actuators %>

<br />

<%= link_to 'Home', root_path %> | 
<%= link_to 'New Actuator', new_actuator_path %>
</div> <!-- .yield -->

app/views/actuators/new.html.erb
<% title "New Actuator" %>

<div class="yield">
<h1>New actuator</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Home', root_path %> | 
<%= link_to 'Actuators', actuators_path %>
</div> <!-- .yield -->

app/views/actuators/show.html.erb
<% title "Show Actuator" %>

<div class="yield">
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @actuator.name %>
</p>

<p>
  <b>Description:</b>
  <% if @actuator.description.nil? %>None<% else %>
  <%= @actuator.description %>
  <% end %>
</p>

<p>
  <b>Manufacturer:</b>
  <%= @actuator.manufacturer %>
</p>

<p>
  <b>Model:</b>
  <%= @actuator.model %>
</p>

<p>
  <b>Valid Values:</b>
  <%= @actuator.valid_values %>
</p>

<p>
  <b><%= link_to "Command", edit_actuator_commands_path(@actuator) %>:</b>
  <%= @actuator.command.data rescue nil %>
</p>

<%= link_to 'Home', root_path %> | 
<%= link_to 'Actuators', actuators_path %> | 
<%= link_to 'Edit', edit_actuator_path(@actuator) %>
</div> <!-- .yield -->

app/views/actuators/valid_values.html.erb
Valid Values:
<%= @vv %><br/>