config/routes.rb
Seeu::Application.routes.draw do

  # RESTful routes
  resources :manufacturers do
    resources :models
  end

  resources :rules

  resources :actuators do
	  resource :commands
  end

  resources :sensors do
	  resources :readings
  end

  # routes that retrieve information about sensors and actuators via JSON
  match '/sensors/:id/valid_values' => 'sensors#valid_values'
  match '/sensors/:id/valid_values_string' => 'sensors#valid_values_string'
  match '/sensors/get_id_from_name/:name' => 'sensors#get_id_from_name'
  match '/sensors/get_values_from_name/:name' => 'sensors#get_values_from_name'
  match '/sensors/get_values_string_from_name/:name' => 'sensors#get_values_string_from_name'

  match '/actuators/:id/valid_values' => 'actuators#valid_values'
  match '/actuators/:id/valid_values_string' => 'actuators#valid_values_string'
  match '/actuators/get_values_from_name/:name' => 'actuators#get_values_from_name'

  # machine readable page (only the command--no additional markup)
  match '/actuators/:id/command' => 'commands#command'

  # feedback and about
  match 'feedback', :to => 'home#feedback', :as => 'feedback'
  match 'about', :to => 'home#about', :as => 'about'
  match 'study', :to => 'home#study', :as => 'study'

  # set the document root to app/view/home/index.html.erb
	root :to => "home#index"

  # route all invalid URLs to document root
  match '*a' => redirect('/') # send all random routes to root
end

app/models/command.rb
class Command < ActiveRecord::Base
	belongs_to :actuator
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  # GET /commands
  # GET /commands.xml
  def index
		@actuator = Actuator.find(params[:actuator_id])
    @commands = Command.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @commands }
    end
  end

  # GET /commands
  # GET /commands/1.xml
  def show
	  @actuator = Actuator.find(params[:actuator_id])
#	  @command = @actuator.command.find(params[:actuator_id])
	  @command = @actuator.command

    respond_to do |format|
      format.html { }
      format.html { render :layout => false }
      format.xml  { render :xml => @command }
    end
  end

  # GET /commands/new
  # GET /commands/new.xml
  def new
	  @actuator = Actuator.find(params[:actuator_id])
    @command = Command.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @command }
    end
  end

  # GET /commands/1/edit
  def edit
	  @actuator = Actuator.find(params[:actuator_id])
#    @command = Command.find(params[:actuator_id])
	  @command = @actuator.command
  end

  # POST /commands
  # POST /commands.xml
  def create
	  @actuator = Actuator.find(params[:actuator_id])
    @command = Command.new(params[:command].each_value(&:strip!))

    respond_to do |format|
      if @command.save
        format.html { redirect_to(@command, :notice => 'Command was successfully created.') }
        format.xml  { render :xml => @command, :status => :created, :location => @command }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @command.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /commands/1
  # PUT /commands/1.xml
  def update
	  @actuator = Actuator.find(params[:actuator_id])
    @command = @actuator.command
#		@command = Command.find(params[:id])

    respond_to do |format|
      if @command.update_attributes(params[:command].each_value(&:strip!))
        format.html { redirect_to(actuator_commands_path(@actuator), :notice => 'Command was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @command.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.xml
  def destroy
	  @actuator = Actuator.find(params[:actuator_id])
    @command = Command.find(params[:id])
    @command.destroy

    respond_to do |format|
      format.html { redirect_to(commands_url) }
      format.xml  { head :ok }
    end
  end

  # machine readable version with no layout
  # GET /command
  def command
	  @actuator = Actuator.find(params[:id])
	  @command = @actuator.command

    respond_to do |format|
      format.html { render :layout => false }
    end
  end

end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/views/commands/_form.html.erb
<%= form_for(@command, :url => actuator_commands_path(@actuator)) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% @command.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :data %><br />
    <%= f.text_field :data %>
  </div>
  <div class="field" style="display:none">
    <%= f.label :actuator_id %><br />
    <%= f.text_field :actuator_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/commands/command.html.erb
<% if @command.nil? or @command.data.nil? %>
OFF
<% else %>
<%= @command.data rescue nil %>
<% end %>

app/views/commands/edit.html.erb
<div class="yield">
<h1>Editing command</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Home', root_path %> | 
<%= link_to 'Actuators', actuators_path %> | 
<%= link_to 'Back to command', actuator_commands_path(@actuator) %>
</div> <!-- .yield -->

app/views/commands/new.html.erb
<div class="yield">
<h1>New command</h1>

<%= render 'form' %>

<br/>
<%= link_to 'Home', root_path %> | 
<%= link_to 'Actuators', actuators_path %> | 
<%= link_to 'Back', commands_path %>
</div> <!-- .yield -->

app/views/commands/show.html.erb
<% title "Command" %>

<div class="yield">
<div>
Command: 
<% if @command.nil? or @command.data.nil? %>
OFF
<% else %>
<%= @command.data rescue nil %>
<% end %>
</div>

<br/>

<%= link_to 'Home', root_path %> |
<%= link_to 'Back to actuator', actuator_path(@actuator) %> |
<%= link_to 'Edit command', edit_actuator_commands_path(@actuator) %>
</div> <!-- .yield -->